name: Bandit

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    - v2m*

permissions:
  contents: read

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
      - name: Bandit
        run: uvx bandit -r -lll -ii .
