name: CDK Nag

on:
  workflow_dispatch:
  push:
    paths:
    - "deploy/**"
    branches:
    - main
  pull_request:
    paths:
    - "deploy/**"
    branches:
    - main
    - v2m*

permissions:
  contents: read

jobs:
  cdk-nag:
    env:
      CDK_DEFAULT_REGION: eu-west-1
      CDK_DEFAULT_ACCOUNT: 111111111111
      GITHUB_ACTIONS: true
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
      - name: Install CDK
        run: |
          npm install -g aws-cdk cdk-nag
          cdk --version
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
      - name: Install Requirements
        run: uv sync --group deploy
      - name: CDK Synth
        run: |
          npx cdk synth
